# Generated by Django 5.2.7 on 2025-10-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('contract', 'Contract'), ('casual', 'Casual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
